mascotitas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('perfiles/', include('perfiles.urls', namespace='perfiles')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('usuario/', include('users.urls', namespace='users')),  

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perfiles/urls.py
from .views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'perfiles'

urlpatterns = [
    path('<uuid:pk>/', PerfilDetailView.as_view(), name='perfil-detail'),
    path('<uuid:pk>/editar/', PerfilUpdateView.as_view(), name='perfil-update'),
    path('<uuid:pk>/activar/', PerfilActivateView.as_view(), name='perfil-activate'),
    path('crear/', PerfilCreateView.as_view(), name='perfil-create'),
    path('<uuid:pk>/cargar-imagen/', ImagenCreateView.as_view(), name='imagen-create'),
    path('', PerfilListView.as_view(), name='perfil-list'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserDetailView

app_name = 'users'

urlpatterns = [
    path('', UserDetailView.as_view(), name='user_profile'),
]

perfiles/models.py
import uuid
from django.db import models
from django.utils.crypto import get_random_string
from users.models import User


def generate_random_string():
    return get_random_string(12)


class Perfil(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre = models.CharField(max_length = 200, blank=False, null=True)
    numero_de_telefono = models.CharField(
        max_length = 50,
        blank=True,
        null=True,
        help_text="Este número podría servir para contactar a su humano en caso de que se extravíe."
    )
    fecha_de_nacimiento = models.DateField(null=True, blank=True)
    ubicacion = models.CharField(max_length=255, blank=True)
    biografia = models.TextField(max_length=500, blank=True)
    fecha_de_creacion = models.DateField(auto_now_add=True, db_index=True, blank=True, null=True)
    humano = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True)
    codigo_de_activacion = models.CharField(max_length=10, default=generate_random_string)

    @property
    def profile_picture(self):
        return self.imagenes.filter(is_profile_picture=True).first()

    def __str__(self):
        if self.nombre:
            return self.nombre
        return id


class Imagen(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    perfil = models.ForeignKey(Perfil, on_delete = models.CASCADE, related_name='imagenes', null=True, blank=True)
    imagen = models.ImageField(verbose_name='imagen', upload_to='images/', null=True, blank=True)
    descripcion = models.TextField(max_length=500, blank=True)
    is_profile_picture = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['perfil', 'is_profile_picture'], name="unique_profile_picture")
        ]

users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    ubicacion = models.CharField(max_length=255, blank=True)
    numero_de_telefono = models.CharField(max_length = 50, blank=True, null=True)
    fecha_de_nacimiento = models.DateField(null=True, blank=True)

perfiles/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from .models import Perfil

class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['nombre', 'numero_de_telefono', 'fecha_de_nacimiento', 'ubicacion', 'biografia']
        widgets = {
            'fecha_de_nacimiento': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(PerfilForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Guardar', css_class='btn-primary mt-2'))
        self.helper.layout = Layout(
            Row(
                Column('nombre', css_class='form-group col-md-6 mb-2'),
                Column('numero_de_telefono', css_class='form-group col-md-6 mb-2'),
            ),
            Row(
                Column('fecha_de_nacimiento', css_class='form-group col-md-6 mb-2'),
                Column('ubicacion', css_class='form-group col-md-6 mb-2'),
            ),
            'biografia',
        )



class ActivateForm(forms.Form):
    codigo_de_activacion = forms.CharField(max_length=12, min_length=12, required=True)

    def __init__(self, *args, **kwargs):
        super(ActivateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Activar', css_class='btn-primary mt-2'))
        self.helper.layout = Layout(
            Row(
                Column('codigo_de_activacion', css_class='form-group col-md-12 mb-0'),
            ),
        )

perfiles/views.py
from django.views.generic import DetailView, ListView, CreateView, UpdateView, FormView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from stronghold.views import StrongholdPublicMixin
from .models import Perfil, Imagen
from .forms import PerfilForm, ActivateForm
# Create your views here.

class PerfilDetailView(StrongholdPublicMixin, DetailView):
    model = Perfil
    def get(self, request, *args, **kwargs):
        if self.get_object().humano:
            return super().get(request, *args, **kwargs)
        else:
            return redirect("perfiles:perfil-activate", pk=self.get_object().pk)


class PerfilActivateView(FormView):
    form_class = ActivateForm
    template_name = "perfiles/perfil_activate.html"
    def get_success_url(self):
        return reverse('perfiles:perfil-detail', kwargs={'pk': self.get_object().pk})
    
    def get_object(self):
        return get_object_or_404(Perfil, pk=self.kwargs.get("pk"))
    
    def form_valid(self, form):
        perfil = self.get_object()
        if form.cleaned_data.get("codigo_de_activacion") == perfil.codigo_de_activacion:
            perfil.humano = self.request.user
            perfil.save()
        else:
            messages.warning(self.request, "El código ingresado no es válido. Tenga en cuenta que se distinguen mayúsculas y minúsculas.")
        return super().form_valid(form)
    

class PerfilCreateView(CreateView):
    model = Perfil
    form_class = PerfilForm

    def get_success_url(self):
        return reverse('perfiles:perfil-detail', kwargs={'pk': self.object.pk})


class PerfilUpdateView(UserPassesTestMixin, UpdateView):
    model = Perfil
    fields = ['nombre', 'numero_de_telefono', 'fecha_de_nacimiento', 'ubicacion', 'biografia']

    def get_success_url(self):
        return reverse('perfiles:perfil-detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.humano = self.request.user
        return super().form_valid(form)

    def test_func(self):
        if self.get_object().humano:
            if self.get_object().humano == self.request.user:
                return True
            return False
        return True


class PerfilListView(StrongholdPublicMixin, ListView):
    model = Perfil
    context_object_name = 'perfiles'


class ImagenDetailView(StrongholdPublicMixin, DetailView):
    model = Imagen


class ImagenCreateView(CreateView):
    model = Imagen
    fields = ['imagen', 'descripcion', 'is_profile_picture']

    def get_success_url(self):
        return reverse('perfiles:perfil-detail', kwargs={'pk': self.object.perfil.pk})

    def form_valid(self, form):
        form.instance.perfil = get_object_or_404(Perfil, pk=self.kwargs['pk'])
        return super().form_valid(form)


class ImagenListView(ListView):
    model = Imagen
    context_object_name = 'imagenes'

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from .models import User

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User

    def get_object(self):
        return self.request.user

mascotitas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Mascotitas!</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans" rel="stylesheet">
    <link href="{% static 'css/fontawesome/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Mas<span>cotitas!</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'users:user_profile' %}"><i class="fas fa-user"></i> {{ request.user }}</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Iniciar Sesión</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <div class="container mt-5 pt-5">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-dismissible">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content_wrapper %}{% endblock %}
    </div>

    <footer class="footer mt-auto py-3 bg-light">
        <div class="container text-center">
            ©2024 Mascotitas. Todos los derechos reservados.
        </div>
    </footer>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/scrollax.min.js' %}"></script>
    <script src="{% static 'contactform/contactform.js' %}"></script>
</body>
</html>

mascotitas/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content_wrapper %}
<div class="container mt-4">
    <header class="jumbotron my-4">
        <h1 class="display-3">¡Bienvenido a Mascotitas!</h1>
        <p class="lead">Un lugar donde la adopción responsable y el amor por los animales se encuentran.</p>
        <a href="{% url 'perfiles:perfil-list' %}" class="btn btn-primary btn-lg">Explora las mascotas disponibles para adopción</a>
    </header>
    
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4">
                <img class="card-img-top img-fluid" src="{% static 'img/perro.jpg' %}" alt="Adopción responsable">
                <div class="card-body">
                    <h4 class="card-title">Adopción Responsable</h4>
                    <p class="card-text">Descubre cómo adoptar una mascota y qué considerar para asegurarte de que estás listo.</p>
                    <a href="#" class="btn btn-outline-primary">Aprende más</a>
                </div>
            </div>
        </div>
        
        <div class="col-md-4">
            <div class="card mb-4">
                <img class="card-img-top img-fluid" src="{% static 'img/transito.jpg' %}" alt="Seguimiento de animales">
                <div class="card-body">
                    <h4 class="card-title">Seguimiento de Animales</h4>
                    <p class="card-text">Entérate de cómo llevamos el seguimiento de los animales en tránsito y cómo puedes contribuir.</p>
                    <a href="#" class="btn btn-outline-primary">Descubre cómo</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card mb-4">
                <img class="card-img-top img-fluid" src="{% static 'img/perfil.jpg' %}" alt="Perfil de mascotas">
                <div class="card-body">
                    <h4 class="card-title">Perfiles de Mascotas</h4>
                    <p class="card-text">Crea un perfil para tu mascota, comparte fotos y conéctate con otros amantes de los animales.</p>
                    <a href="{% url 'perfiles:perfil-list' %}" class="btn btn-outline-primary">Empieza aquí</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

perfiles/templates/perfiles/imagen_form.html
{% extends 'base.html' %}
{% load static %}
{% block content_wrapper %}
    <form enctype="multipart/form-data" method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
{% endblock %}

perfiles/templates/perfiles/perfil_activate.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block content_wrapper %}
    <h1>Activar nuevo perfil</h1>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% crispy form %}
    </form>
{% endblock %}

perfiles/templates/perfiles/perfil_card.html
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title font-weight-bold">{{ perfil.nombre }}</h5>
        <p class="card-text">
            <strong>Mi humano es:</strong> {{ perfil.humano|default:'No tengo humano :(' }}
        </p>
        {{ perfil.codigo_de_activacion }}
        <a href="{% url 'perfiles:perfil-detail' perfil.pk %}" class="btn btn-primary">Ver detalle</a>
    </div>
</div>

perfiles/templates/perfiles/perfil_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content_wrapper %}
  <div class="container mt-4">
    {% comment %} {% if object.profile_picture %}
      <img src="{{ object.profile_picture.imagen.url }}" class="img-fluid" alt="Profile picture" />
    {% endif %} {% endcomment %}
    {% if object.imagenes.all %}
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          {% for imagen in object.imagenes.all %}
            <div class="carousel-item {% if forloop.first %}{% endif %}">
              <img src="{{ imagen.imagen.url }}" class="d-block w-100" alt="{{ imagen.descripcion }}" />
            </div>
          {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    {% else %}
      <p>No hay imágenes para mostrar.</p>
    {% endif %}

    <h1>{{ object.nombre }}</h1>
    <p>Número de contacto: {{ object.numero_de_telefono }}</p>
    <p>Fecha de nacimiento: {{ object.fecha_de_nacimiento|date:'Y-m-d' }}</p>
    <p>Ubicación: {{ object.ubicacion }}</p>
    <p>Biografía: {{ object.biografia }}</p>
    <p>Humano: {{ object.humano }}</p>

    <div class="d-flex justify-content-end">
      <a href="{% url 'perfiles:perfil-update' object.pk %}" class="btn btn-success mr-2">Editar perfil</a>
      <a href="{% url 'perfiles:imagen-create' object.pk %}" class="btn btn-info">Cargar imagen</a>
    </div>

    <div class="fb-comments" data-href="https://prueba-tp-django.herokuapp.com/" data-width="" data-numposts="5"></div>
  </div>
{% endblock %}

{% block extra_js %}
  <div id="fb-root"></div>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v12.0&appId=408165317356447&autoLogAppEvents=1" nonce="ujJNYwjz"></script>
{% endblock %}

perfiles/templates/perfiles/perfil_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block content_wrapper %}
    <h1>Crea un nuevo perfil</h1>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% crispy form %}
    </form>
{% endblock %}

perfiles/templates/perfiles/perfil_list.html
{% extends 'base.html' %}
{% load static %}

{% block content_wrapper %}
<div class="container mt-4">
    <div class="d-flex justify-content-end mb-4">
        <a href="{% url 'perfiles:perfil-create' %}" class="btn btn-success">Agregar perfil</a>
    </div>
    {% for perfil in perfiles %}
        {% include "perfiles/perfil_card.html" %}
    {% empty %}
        <p class="text-center">No hay perfiles disponibles.</p>
    {% endfor %}
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'base.html' %}

{% block content_wrapper %}
<div class="container">
    <h2>Perfil de Usuario</h2>
    <div class="row">
        <div class="col-md-6">
            <p><strong>Username:</strong> {{ object.username }}</p>
            <p><strong>Email:</strong> {{ object.email }}</p>
            <p><strong>Ubicación:</strong> {{ object.ubicacion }}</p>
            <p><strong>Número de teléfono:</strong> {{ object.numero_de_telefono }}</p>
            <p><strong>Fecha de nacimiento:</strong> {{ object.fecha_de_nacimiento|date:"d/m/Y" }}</p>
        </div>
    </div>
</div>
{% endblock %}